
package com.example.springserviceclient.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.springservice.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @return
     *     returns java.util.List<com.example.springserviceclient.service.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "all", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.All")
    @ResponseWrapper(localName = "allResponse", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.AllResponse")
    @Action(input = "http://service.springservice.example.com/ProductService/allRequest", output = "http://service.springservice.example.com/ProductService/allResponse")
    public List<Product> all();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.springserviceclient.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateOrUpdate", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.UpdateOrUpdate")
    @ResponseWrapper(localName = "updateOrUpdateResponse", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.UpdateOrUpdateResponse")
    @Action(input = "http://service.springservice.example.com/ProductService/updateOrUpdateRequest", output = "http://service.springservice.example.com/ProductService/updateOrUpdateResponse")
    public Product updateOrUpdate(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

}
