
package com.example.springserviceclient.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentService", targetNamespace = "http://service.springservice.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.springserviceclient.service.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.UpdateResponse")
    @Action(input = "http://service.springservice.example.com/StudentService/updateRequest", output = "http://service.springservice.example.com/StudentService/updateResponse")
    public Student update(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.DeleteResponse")
    @Action(input = "http://service.springservice.example.com/StudentService/deleteRequest", output = "http://service.springservice.example.com/StudentService/deleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.springserviceclient.service.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.SaveResponse")
    @Action(input = "http://service.springservice.example.com/StudentService/saveRequest", output = "http://service.springservice.example.com/StudentService/saveResponse")
    public Student save(
        @WebParam(name = "arg0", targetNamespace = "")
        Student arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.example.springserviceclient.service.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "all", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.All")
    @ResponseWrapper(localName = "allResponse", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.AllResponse")
    @Action(input = "http://service.springservice.example.com/StudentService/allRequest", output = "http://service.springservice.example.com/StudentService/allResponse")
    public List<Student> all();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.springserviceclient.service.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://service.springservice.example.com/", className = "com.example.springserviceclient.service.FindByIdResponse")
    @Action(input = "http://service.springservice.example.com/StudentService/findByIdRequest", output = "http://service.springservice.example.com/StudentService/findByIdResponse")
    public Student findById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
